# contextpilot

> Auto-generated by **ContextPilot** — AI Context Management Platform
> Generated: 20/7/2026
> Coverage Score: **30/100**

Project built with TypeScript, CSS
Package manager: `pnpm`

## Tech Stack

- **TypeScript** — 100% of codebase
- **CSS** — 24% of codebase

### Frameworks

## Guardrails

### DO NOT:
- Add new dependencies without explicit approval
- Modify configuration files without user confirmation
- Use `any` type without explanatory comment
- Remove existing tests
- Refactor code outside the scope of the current task
- Leave console.log statements in production code
- Use deprecated APIs or packages

## Commands

### Development
- `npm run dev` — Start development mode
- `npm run build` — Build the project

### Testing
- `npm test` — Run tests
- `npm run test:watch` — Run tests in watch mode
- `npm run test:coverage` — Run tests with coverage

### Code Quality
- `npm run typecheck` — Check TypeScript types
- `npm run lint` — Lint the codebase
- `npm run format` — Format code

## Architecture

### Directory Structure
```
contextpilot/
├── docs/         # Documentation
├── .github/      # CI/CD configuration
├── examples/
├── media/
├── packages/
├── templates/
```

## Coding Conventions

- **TypeScript:** Strict mode enabled. Use explicit types. Avoid `any`.
- **Exports:** Prefer named exports over default exports.
- **Imports:** Group imports: external → internal → types. Use absolute imports.

- **File Naming:** `kebab-case` for files, `PascalCase` for components, `camelCase` for functions/variables.
- **Testing:** Unit tests alongside source files. Integration tests in `tests/` directory.
- **Commits:** Conventional commits (`feat:`, `fix:`, `refactor:`, `docs:`).

## References


Key files:
- `CONTRIBUTING.md` — Contribution guidelines